CREATE TABLE IF NOT EXISTS PERSON
(
  ID            INTEGER IDENTITY PRIMARY KEY,
  FIRST_NAME    varchar(255),
  LAST_NAME     varchar(255),
  DATE_OF_BIRTH DATETIME,
  PROFESSION    varchar(255)
);

CREATE TABLE IF NOT EXISTS FLAT
(
  ID      INTEGER IDENTITY PRIMARY KEY,
  AREA    INTEGER,
  ADDRESS varchar(255),
);

CREATE TABLE IF NOT EXISTS ROOM
(
  ID            INTEGER IDENTITY PRIMARY KEY,
  AREA          INTEGER,
  WINDOWS_COUNT INTEGER,
  FLAT          INTEGER REFERENCES FLAT,
  FLAT_KEY      INTEGER
);
